//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlawHUD.Installer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlawHUD.Installer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/criticalflaw/flawhud/archive/master.zip.
        /// </summary>
        internal static string app_download {
            get {
                return ResourceManager.GetString("app_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://raw.githubusercontent.com/criticalflaw/flawhud/master/README.md.
        /// </summary>
        internal static string app_readme {
            get {
                return ResourceManager.GetString("app_readme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://raw.githubusercontent.com/CriticalFlaw/FlawHUD.Installer/master/Update.xml.
        /// </summary>
        internal static string app_update {
            get {
                return ResourceManager.GetString("app_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \flawhud\materials\console\.
        /// </summary>
        internal static string dir_console {
            get {
                return ResourceManager.GetString("dir_console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \flawhud\resource\ui.
        /// </summary>
        internal static string dir_resource_ui {
            get {
                return ResourceManager.GetString("dir_resource_ui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \flawhud\scripts.
        /// </summary>
        internal static string dir_scripts {
            get {
                return ResourceManager.GetString("dir_scripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tf/custom directory needs to be set in order to use the installer..
        /// </summary>
        internal static string error_app_directory {
            get {
                return ResourceManager.GetString("error_app_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Not Set.
        /// </summary>
        internal static string error_app_directory_title {
            get {
                return ResourceManager.GetString("error_app_directory_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while installing FlawHUD..
        /// </summary>
        internal static string error_app_install {
            get {
                return ResourceManager.GetString("error_app_install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading FlawHUD settings..
        /// </summary>
        internal static string error_app_load {
            get {
                return ResourceManager.GetString("error_app_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while resetting FlawHUD settings..
        /// </summary>
        internal static string error_app_reset {
            get {
                return ResourceManager.GetString("error_app_reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while saving FlawHUD settings..
        /// </summary>
        internal static string error_app_save {
            get {
                return ResourceManager.GetString("error_app_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while uninstalling FlawHUD..
        /// </summary>
        internal static string error_app_uninstall {
            get {
                return ResourceManager.GetString("error_app_uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while checking the FlawHUD version number..
        /// </summary>
        internal static string error_app_version {
            get {
                return ResourceManager.GetString("error_app_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: .
        /// </summary>
        internal static string error_info {
            get {
                return ResourceManager.GetString("error_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while applying the color settings..
        /// </summary>
        internal static string error_set_colors {
            get {
                return ResourceManager.GetString("error_set_colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while applying the custom fonts setting..
        /// </summary>
        internal static string error_set_fonts {
            get {
                return ResourceManager.GetString("error_set_fonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while applying the main menu background setting..
        /// </summary>
        internal static string error_set_menu_backgrounds {
            get {
                return ResourceManager.GetString("error_set_menu_backgrounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while applying the main menu class image setting..
        /// </summary>
        internal static string error_set_menu_class_image {
            get {
                return ResourceManager.GetString("error_set_menu_class_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while applying the spy disguise image setting..
        /// </summary>
        internal static string error_set_spy_disguise_image {
            get {
                return ResourceManager.GetString("error_set_spy_disguise_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while applying the transparent viewmodels setting..
        /// </summary>
        internal static string error_set_transparent_viewmodels {
            get {
                return ResourceManager.GetString("error_set_transparent_viewmodels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while applying the crosshair settings..
        /// </summary>
        internal static string error_set_xhair {
            get {
                return ResourceManager.GetString("error_set_xhair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while applying the crosshair pulse setting..
        /// </summary>
        internal static string error_set_xhair_pulse {
            get {
                return ResourceManager.GetString("error_set_xhair_pulse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \flawhud\cfg\hud.cfg.
        /// </summary>
        internal static string file_cfg {
            get {
                return ResourceManager.GetString("file_cfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \flawhud\scripts\chapterbackgrounds.txt.
        /// </summary>
        internal static string file_chapterbackgrounds {
            get {
                return ResourceManager.GetString("file_chapterbackgrounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \flawhud\resource\clientscheme.res.
        /// </summary>
        internal static string file_clientscheme {
            get {
                return ResourceManager.GetString("file_clientscheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \flawhud\resource\scheme\clientscheme_colors.res.
        /// </summary>
        internal static string file_clientscheme_colors {
            get {
                return ResourceManager.GetString("file_clientscheme_colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \flawhud\scripts\hudanimations_custom.txt.
        /// </summary>
        internal static string file_hudanimations {
            get {
                return ResourceManager.GetString("file_hudanimations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \flawhud\scripts\hudlayout.res.
        /// </summary>
        internal static string file_hudlayout {
            get {
                return ResourceManager.GetString("file_hudlayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \flawhud\resource\ui\mainmenuoverride.res.
        /// </summary>
        internal static string file_mainmenuoverride {
            get {
                return ResourceManager.GetString("file_mainmenuoverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \flawhud\resource\ui\hudplayerhealth.res.
        /// </summary>
        internal static string file_playerhealth {
            get {
                return ResourceManager.GetString("file_playerhealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An existing flawhud-master folder has been found. To avoid conflicts, a backup has been created..
        /// </summary>
        internal static string info_create_backup {
            get {
                return ResourceManager.GetString("info_create_backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Created.
        /// </summary>
        internal static string info_create_backup_title {
            get {
                return ResourceManager.GetString("info_create_backup_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your tf/custom folder. If a valid directory is not provided, the options to install and modify FlawHUD will not be available..
        /// </summary>
        internal static string info_folder_browser {
            get {
                return ResourceManager.GetString("info_folder_browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Complete.
        /// </summary>
        internal static string info_install_complete {
            get {
                return ResourceManager.GetString("info_install_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlawHUD has been successfully installed.
        /// </summary>
        internal static string info_install_complete_desc {
            get {
                return ResourceManager.GetString("info_install_complete_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall Complete.
        /// </summary>
        internal static string info_uninstall_complete {
            get {
                return ResourceManager.GetString("info_uninstall_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlawHUD has been successfully uninstalled.
        /// </summary>
        internal static string info_uninstall_complete_desc {
            get {
                return ResourceManager.GetString("info_uninstall_complete_desc", resourceCulture);
            }
        }
    }
}
